### ISSUE TITLE
我用npm i 然后运行报错啊

### ISSUE THREAD

**Issue by GuiYuanLu** [An0510/react-app-travel#1]
为什么这是 作者那边可以正常运行吗

**Comment by An0510** [comment]
加载依赖应该不会报错吧 看一下是不是用了vpn，或者改用淘宝镜像源试一下。如果是不能运行就把项目里的x-icode改为9552115FA6CEB117。因为是调用别人的接口哈

**Comment by GuiYuanLu** [comment]
> 

还是不行 我用了淘宝镜像源 没有开vpn

**Comment by An0510** [comment]
搜一下控制台报错信息看看

**Comment by GuiYuanLu** [comment]
> 搜一下控制台报错信息看看
`bash-3.2$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-app-travel@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0" from react-credit-cards@0.8.3
npm ERR! node_modules/react-credit-cards
npm ERR!   react-credit-cards@"^0.8.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/ruiliu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ruiliu/.npm/_logs/2022-06-20T03_34_22_389Z-debug-0.log`

**Comment by An0510** [comment]
百度或者google一下报错的前几行。一般都能解决。

**Comment by GuiYuanLu** [comment]
`npm config set legacy-peer-deps true

npm install  --force
`
我先用的这两行然后就可以了 本来百度没找到就换谷歌了就找到了

**Comment by An0510** [comment]
嗯嗯

**Comment by GuiYuanLu** [comment]
项目跑起来了 但是你这个项目里面好多报错 你跑一下看看

**Comment by An0510** [comment]
你说的应该是启动的时候控制台报错的那些eslint校验吧 你可以关了试试 项目跑起来是没报错的 localhost:3000
